### ISSUE TITLE
Database link not working

### ISSUE THREAD

**Issue by tonyreina** [boutroslab/cld_docker#8]
http://www.dkfz.de/signaling/crispr-downloads/DATABASES

I'm trying to download from the database link, but it appears the link is no longer valid. Could these be uploaded to something like Zenodo?

**Comment by canfirtina** [comment]
I also opened a similar issue here: https://github.com/boutroslab/cld/issues/20

It appears that there is another link presumably for the same datasets: http://www.e-crisp.org/E-CRISP/CLD-DB/. However, the datasets cannot be downloaded due to a permission issue.

Edit: The permission issue is now solved. You can use the e-crips link above to download the datasets of interest.

**Comment by chaozhangGS** [comment]
I use the built-in make_database command to download data from ensemble and create genome data de novo. I get an error. How should I solve it?
Can you provide a valid download link for the built genome?
ERROR
```
Sorting block of length 34753998 for bucket 6
(Using difference cover)
Time to join reference sequences: 00:03:53
bmax according to bmaxDivN setting: 753430362
Using parameters --bmax 565072772 --dcv 1024
Doing ahead-of-time memory usage test
Killed
The database for the organism homo_sapiens has been built in the following path:
/var/www/homo_sapiens
```
